using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SaveDataGenerator
{
    [Generator]
    public class SaveDataSourceGenerator : ISourceGenerator
    {
        private static readonly HashSet<string> BannedNamespaces = new()
        {
            "UnityEngine", "System", "UniRx", "Newtonsoft", "Cysharp", "VContainer", "Unity", "TMPro"
        };

        public void Initialize(GeneratorInitializationContext context) { }

        public void Execute(GeneratorExecutionContext context)
        {
            foreach (var tree in context.Compilation.SyntaxTrees)
            {
                var sourceText = tree.GetText().ToString();
                if (!sourceText.Contains("[SaveData")) continue;

                var semanticModel = context.Compilation.GetSemanticModel(tree);
                var typeDeclarations = tree.GetRoot().DescendantNodes().OfType<TypeDeclarationSyntax>();

                foreach (var typeDecl in typeDeclarations)
                {
                    var typeSymbol = semanticModel.GetDeclaredSymbol(typeDecl) as INamedTypeSymbol;
                    if (typeSymbol is null) continue;
                    if (IsNamespaceBanned(typeSymbol.ContainingNamespace)) continue;

                    bool hasAttr = typeSymbol.GetAttributes().Any(a =>
                        a.AttributeClass?.Name is "SaveData" or "SaveDataAttribute");
                    if (!hasAttr) continue;

                    try
                    {
                        string generatedCode = GenerateSaveData(typeSymbol, context);
                        if (!string.IsNullOrEmpty(generatedCode))
                        {
                            // 🔍 Вывод полного текста файла в консоль / Editor.log
                            Console.WriteLine($"[SaveDataGen] === GENERATED: {typeSymbol.Name}.SaveData.g.cs ===");
                            Console.WriteLine(generatedCode);
                            Console.WriteLine("[SaveDataGen] ================================================");

                            context.AddSource($"{typeSymbol.Name}.SaveData.g.cs", SourceText.From(generatedCode, Encoding.UTF8));
                        }
                    }
                    catch (Exception ex)
                    {
                        context.ReportDiagnostic(Diagnostic.Create(
                            new DiagnosticDescriptor("SDG_E001", "SaveData Gen Error", ex.ToString(), "SaveData", DiagnosticSeverity.Error, true),
                            Location.None));
                    }
                }
            }
        }

        private static bool IsNamespaceBanned(INamespaceSymbol ns)
        {
            var current = ns;
            while (current != null && !current.IsGlobalNamespace)
            {
                if (BannedNamespaces.Contains(current.Name)) return true;
                current = current.ContainingNamespace;
            }
            return false;
        }

        private static string GenerateSaveData(INamedTypeSymbol typeSymbol, GeneratorExecutionContext context)
        {
            var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace ? null : typeSymbol.ContainingNamespace.ToDisplayString();
            var dtoName = $"{typeSymbol.Name}SaveData";

            // Фильтрация членов: только public, не static, без ErrorType
            var members = typeSymbol.GetMembers()
                .Where(m => (m is IFieldSymbol || m is IPropertySymbol) && m.DeclaredAccessibility == Accessibility.Public && !m.IsStatic)
                .Select(m => (Symbol: m, Type: GetSafeType(m)))
                .Where(x => x.Type != null && x.Type.Kind != SymbolKind.ErrorType)
                .Where(x => IsSettable(x.Symbol))
                .ToList();

            if (members.Count == 0) return string.Empty;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable CS0169, CS0649, CS8618");
            
            if (ns != null) sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");

            // 1. DTO Struct
            sb.AppendLine($"    public struct {dtoName}");
            sb.AppendLine("    {");
            foreach (var m in members)
            {
                var serializedType = GetSerializedType(m.Type, out bool isReactive);
                if (string.IsNullOrEmpty(serializedType)) continue;
                sb.AppendLine($"        public {serializedType} {m.Symbol.Name} {{ get; set; }}");
            }
            sb.AppendLine("    }");

            // 2. Extension Methods
            sb.AppendLine($"    public static class {typeSymbol.Name}SaveExtensions");
            sb.AppendLine("    {");
            
            // ToSaveData
            sb.AppendLine($"        public static {dtoName} ToSaveData(this {typeSymbol.Name} model)");
            sb.AppendLine("        {");
            sb.AppendLine($"            return new {dtoName}");
            sb.AppendLine("            {");
            foreach (var m in members)
            {
                var serializedType = GetSerializedType(m.Type, out bool isReactive);
                if (string.IsNullOrEmpty(serializedType)) continue;
                sb.AppendLine($"                {m.Symbol.Name} = model.{m.Symbol.Name}{(isReactive ? ".Value" : "")},");
            }
            sb.AppendLine("            };");
            sb.AppendLine("        }");

            // ApplySaveData
            sb.AppendLine($"        public static void ApplySaveData(this {typeSymbol.Name} model, {dtoName} data)");
            sb.AppendLine("        {");
            foreach (var m in members)
            {
                var serializedType = GetSerializedType(m.Type, out bool isReactive);
                if (string.IsNullOrEmpty(serializedType)) continue;
                sb.AppendLine($"            model.{m.Symbol.Name}{(isReactive ? ".Value" : "")} = data.{m.Symbol.Name};");
            }
            sb.AppendLine("        }");
            sb.AppendLine("    }");

            sb.AppendLine("}");
            sb.AppendLine("#pragma warning restore");

            return sb.ToString();
        }

        private static ITypeSymbol? GetSafeType(ISymbol member) => member switch
        {
            IPropertySymbol p => p.Type,
            IFieldSymbol f => f.Type,
            _ => null
        };

        private static bool IsSettable(ISymbol symbol) => symbol switch
        {
            IPropertySymbol ps => ps.SetMethod != null,
            IFieldSymbol fs => !fs.IsReadOnly && !fs.IsConst,
            _ => false
        };

        private static string GetSerializedType(ITypeSymbol type, out bool isReactive)
        {
            isReactive = false;
            if (type == null || type.Kind == SymbolKind.ErrorType) return string.Empty;

            if (type is INamedTypeSymbol named)
            {
                string defName = named.OriginalDefinition?.ToDisplayString() ?? string.Empty;
                string typeName = named.Name;

                // Пропускаем коллекции (пока не поддерживаем сериализацию)
                if (defName.Contains("ReactiveCollection") || typeName.Contains("ReactiveCollection"))
                    return string.Empty;

                // UniRx ReactiveProperty<T>
                if ((defName.Contains("ReactiveProperty") || typeName.Contains("ReactiveProperty")) && named.TypeArguments.Length > 0)
                {
                    var arg = named.TypeArguments[0];
                    if (arg == null || arg.Kind == SymbolKind.ErrorType) return string.Empty;
                    isReactive = true;
                    return arg.ToDisplayString();
                }

                // Кастомные реактивные (Vector3ReactiveProperty и т.д.)
                if (typeName.EndsWith("ReactiveProperty"))
                {
                    var valueProp = type.GetMembers("Value").OfType<IPropertySymbol>().FirstOrDefault();
                    if (valueProp?.Type == null || valueProp.Type.Kind == SymbolKind.ErrorType) return string.Empty;
                    isReactive = true;
                    return valueProp.Type.ToDisplayString();
                }
            }

            return type.ToDisplayString();
        }
    }
}